@startuml
top to bottom direction

rectangle "crosscutting" #LightBlue {
    package "crosscutting " #LightGrey {
        [ *.ddd-api]
        [*.exceptions.*]
    }
}

rectangle "domain" #LightBlue {

    package "model" #LightGrey {
        [*domain.model.*]
    }
    package "readonly" #LightGrey{
        [*.domain.query.*]
    }
    package "services" #LightGrey {
        [*.domains.services.*]
    }
    }
     
rectangle "application" #LightBlue {
    package "services " #LightGrey {
        [*.domainstory.*Impl.java] 
        [*.domainevent.*Impl.java]
      }
    package "ports outbound persistence" #LightGrey {
        [ //Aggregate//Repository.java]
    }
    package "ports outbound queries" #LightGrey {
        [//UseCase//Query.java]
    }
    package "ports outbound dto" #LightGrey {
        [ *.out.*DTO.java] 
        [*.out.*]
    }
    package "ports inbound" #LightGrey {
        [ *.in.*DTO.java]
        [*.in.*]
    }
}

rectangle "adapter" #LightBlue {
    package "persistence" #LightGrey {
        [//Aggregate//RepositoryImpl.java]
    }
    package "messaging" #LightGrey {
        [ *Listener.java] 
        [ *Sender.java]
        [ *Listener.java]-[hidden]-[ *Sender.java]
    }
    package "webservices" #LightGrey  {
        [  *Provider.java]
        [ *Consumer.java]
        [  *Provider.java]-[hidden]-[ *Consumer.java]
    }
    package "user interface" #LightGrey {
        [ *Controller.java]
        [ *Notifier.java]
        [ *Controller.java]-[hidden]-[ *Notifier.java]
    }
    package " environment" #LightGrey {
        [Service Provider]
        [Service Calls]
        [Service Provider]-[hidden]-[Service Calls]
    }
    package "query" #LightGrey {
        [//UseCase//QueryImpl.java]
    }
}

rectangle "configuration " #LightBlue {
    package "configuration" #LightGrey {
        [*.bootstrap.*]
        [*.configuration.*]
        [ *Application.java]
    }

' ***********************
' layout
' ***********************

' layer domain - crosscutting
        [*.domain.query.*]-[hidden]-[ *.ddd-api]

' domain services above query results
        [*.domains.services.*]-[hidden]->[*.domain.query.*]
        [*.domains.services.*]-[hidden]->[*domain.model.*]

' layer application - domain
        [*.domainevent.*Impl.java]-[hidden]->[*.domains.services.*]

' ports aggregates level with ports dto
        [ //Aggregate//Repository.java]-[hidden]->[*.domainevent.*Impl.java]
        [//UseCase//Query.java]-[hidden]->[*.domainevent.*Impl.java]
        [ *.in.*DTO.java]-[hidden]->[*.domainevent.*Impl.java]

' layer application

        [//Aggregate//RepositoryImpl.java]-[hidden]-[ //Aggregate//Repository.java]
        [//UseCase//QueryImpl.java]-[hidden]-[//UseCase//Query.java]
        [*.in.*]-[hidden]-[*.domainevent.*Impl.java]

' layer adapter application
        [Service Calls]-[hidden]-[*.in.*]

' layer adapter
         [//Aggregate//RepositoryImpl.java]-[hidden]-[//UseCase//QueryImpl.java]

' layer deployment - adapter
        [ *Application.java]-[hidden]-[ *Controller.java]

@enduml